site_name: "Harness Terraform Provider"
repo_url: https://github.com/harness/terraform-provider-harness/
edit_uri: https://github.com/harness/terraform-provider-harness/

nav:
  - Home: docs/index.md
  - Resources: docs/resources/*/*.md
  - Data Sources: docs/ata-sources/*/*.md
  - Guides: docs/guides/*/*.md

plugins:
  - techdocs-core
